name: PHP CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.1

      - name: Install
        run: make setup

      - name: Check lint
        run: make lint

      - name: Execute tests via PHPUnit
        run: make test
      - name: Show test coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 83339df1bc319e65f48541a0eb2996eebd4e55a46ed1adc8b860216a023cabf7
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{ github.workplace }}/build/logs/clover.xml:clover
          debug: true
